services:
  db:
    image: postgres:16
    container_name: billing_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: billing_db
    ports:
      - "5433:5432"
      
    volumes:
      - billing_db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  billing_db_data:
